// <auto-generated />
using System;
using GreenThumb.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenThumb.Migrations
{
    [DbContext(typeof(GreenThumbDbContext))]
    [Migration("20231206171343_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GreenThumb.Models.GardenModel", b =>
                {
                    b.Property<int>("GardenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GardenId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("GardenId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Gardens");
                });

            modelBuilder.Entity("GreenThumb.Models.InstructionModel", b =>
                {
                    b.Property<int>("InstructionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructionId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("PlantId")
                        .HasColumnType("int")
                        .HasColumnName("plant_id");

                    b.HasKey("InstructionId");

                    b.HasIndex("PlantId");

                    b.ToTable("Instructions");

                    b.HasData(
                        new
                        {
                            InstructionId = 1,
                            Description = "Water the rose plant 2 times a day, and pour 200 ml of water each time.",
                            Name = "Watering",
                            PlantId = 1
                        },
                        new
                        {
                            InstructionId = 2,
                            Description = "Trim any dead or wilted flowers and leaves from the rose plant using clean pruning shears. Aim to promote healthy growth and maintain a tidy appearance.",
                            Name = "Pruning",
                            PlantId = 1
                        },
                        new
                        {
                            InstructionId = 3,
                            Description = "Place the Monstera Deliciosa in a location with bright, indirect sunlight. Avoid direct sunlight, as it can scorch the leaves.",
                            Name = "Sunlight Exposure",
                            PlantId = 2
                        },
                        new
                        {
                            InstructionId = 4,
                            Description = "Allow the top inch of the soil to dry out between waterings. Water the Monstera when the soil feels slightly dry, and ensure proper drainage to prevent waterlogged roots.",
                            Name = "Soil Moisture",
                            PlantId = 2
                        },
                        new
                        {
                            InstructionId = 5,
                            Description = "After the first bloom, prune back one-third of the lavender plant to encourage bushier growth and more flowers.",
                            Name = "Pruning",
                            PlantId = 3
                        },
                        new
                        {
                            InstructionId = 6,
                            Description = "Plant lavender in well-drained soil to prevent root rot. Add sand or perlite to improve drainage if needed.",
                            Name = "Well-Drained Soil",
                            PlantId = 3
                        },
                        new
                        {
                            InstructionId = 7,
                            Description = "Snake plants thrive in low light but can tolerate indirect sunlight. Keep the plant in a spot with minimal light exposure.",
                            Name = "Low Light Tolerance",
                            PlantId = 4
                        },
                        new
                        {
                            InstructionId = 8,
                            Description = "Water the snake plant sparingly, allowing the soil to dry out completely between waterings. Overwatering can lead to root rot.",
                            Name = "Infrequent Watering",
                            PlantId = 4
                        },
                        new
                        {
                            InstructionId = 9,
                            Description = "Plant sunflowers in a location with full sun exposure for at least 6-8 hours a day for optimal growth and vibrant blooms.",
                            Name = "Sun Exposure",
                            PlantId = 5
                        },
                        new
                        {
                            InstructionId = 10,
                            Description = "As sunflowers grow, provide support for tall stems by staking them to prevent bending or breaking in windy conditions.",
                            Name = "Support for Tall Stems",
                            PlantId = 5
                        },
                        new
                        {
                            InstructionId = 11,
                            Description = "If growing bamboo outdoors, consider containing its spread by planting it within barriers or using a root control system to prevent it from becoming invasive.",
                            Name = "Containment",
                            PlantId = 6
                        },
                        new
                        {
                            InstructionId = 12,
                            Description = "Fertilize bamboo with a balanced fertilizer during the growing season to promote healthy growth. Follow the recommended dosage on the fertilizer package.",
                            Name = "Fertilization",
                            PlantId = 6
                        },
                        new
                        {
                            InstructionId = 13,
                            Description = "Remove faded or spent tulip flowers by deadheading them. This encourages the plant to redirect energy into bulb growth.",
                            Name = "Deadheading",
                            PlantId = 7
                        },
                        new
                        {
                            InstructionId = 14,
                            Description = "Every few years, consider dividing tulip bulbs to prevent overcrowding. Lift the bulbs, separate them, and replant in well-prepared soil.",
                            Name = "Bulb Division",
                            PlantId = 7
                        },
                        new
                        {
                            InstructionId = 15,
                            Description = "Prune lower branches of cannabis plants to improve airflow and reduce the risk of mold and pests.",
                            Name = "Pruning for Airflow",
                            PlantId = 8
                        },
                        new
                        {
                            InstructionId = 16,
                            Description = "If cultivating cannabis indoors, maintain a consistent light schedule during the vegetative and flowering stages, providing 18 hours of light during vegetative growth and 12 hours during flowering.",
                            Name = "Light Schedule",
                            PlantId = 8
                        });
                });

            modelBuilder.Entity("GreenThumb.Models.PlantGardens", b =>
                {
                    b.Property<int>("PlantId")
                        .HasColumnType("int")
                        .HasColumnName("plant_id");

                    b.Property<int>("GardenId")
                        .HasColumnType("int")
                        .HasColumnName("garden_id");

                    b.Property<DateTime>("DateAtGarden")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_at_garden");

                    b.HasKey("PlantId", "GardenId");

                    b.HasIndex("GardenId");

                    b.ToTable("PlantGardens");
                });

            modelBuilder.Entity("GreenThumb.Models.PlantModel", b =>
                {
                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("PlantId");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            PlantId = 1,
                            Description = "Roses are classic flowering plants known for their fragrant and colorful blooms. They come in various colors and varieties, each with its own unique scent and aesthetic appeal. Roses are often used in gardens, bouquets, and as ornamental plants.",
                            Name = "Rose",
                            Type = "Shrub"
                        },
                        new
                        {
                            PlantId = 2,
                            Description = "Monstera deliciosa, also known as the Swiss cheese plant, is a popular tropical houseplant with large, glossy leaves that have distinctive splits and holes. It adds a touch of exotic beauty to indoor spaces and is relatively easy to care for.",
                            Name = "Monstera Deliciosa",
                            Type = "Houseplant"
                        },
                        new
                        {
                            PlantId = 3,
                            Description = "Lavender is a fragrant herb known for its aromatic flowers and silvery-green foliage. It is often cultivated for its essential oils, used in perfumes and aromatherapy. Lavender is also a favorite in gardens, attracting pollinators and adding a soothing scent to the surroundings.",
                            Name = "Lavender",
                            Type = "Shrub"
                        },
                        new
                        {
                            PlantId = 4,
                            Description = "The snake plant, also known as mother-in-law's tongue, is a hardy and low-maintenance indoor plant. It has tall, upright leaves that are often green with variegated patterns. Snake plants are known for their air-purifying qualities and can thrive in low-light conditions.",
                            Name = "Snake Plant",
                            Type = "Succulent"
                        },
                        new
                        {
                            PlantId = 5,
                            Description = "Sunflowers are iconic annual plants with large, vibrant yellow flowers that resemble the sun. They are known for their heliotropic nature, with the flowers turning to face the sun. Sunflowers are commonly grown for their seeds, which are edible and often used in snacks and cooking.",
                            Name = "Sunflower",
                            Type = "Annual"
                        },
                        new
                        {
                            PlantId = 6,
                            Description = "Bamboo is a versatile and fast-growing plant belonging to the grass family. It is known for its tall, slender stems (culms) and is used for various purposes, including construction, furniture, and as a decorative plant. Some bamboo species are also a source of food.",
                            Name = "Bamboo",
                            Type = "Grass"
                        },
                        new
                        {
                            PlantId = 7,
                            Description = "Tulips are spring-blooming flowers with a wide range of colors and shapes. They are bulbous plants and are often associated with the arrival of spring. Tulips are popular in gardens and floral arrangements, symbolizing love and elegance.",
                            Name = "Tulip",
                            Type = "Bulb"
                        },
                        new
                        {
                            PlantId = 8,
                            Description = "Cannabis is a genus of flowering plants, including sativa, indica, and ruderalis species. Known for psychoactive properties due to THC, it has distinctive palmate leaves and resinous flowers. Used historically for medicinal, recreational, and industrial purposes, cannabis contains cannabinoids like CBD. Legal status varies globally.",
                            Name = "Cannabis",
                            Type = "Herb"
                        });
                });

            modelBuilder.Entity("GreenThumb.Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GreenThumb.Models.GardenModel", b =>
                {
                    b.HasOne("GreenThumb.Models.UserModel", "User")
                        .WithOne("Garden")
                        .HasForeignKey("GreenThumb.Models.GardenModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenThumb.Models.InstructionModel", b =>
                {
                    b.HasOne("GreenThumb.Models.PlantModel", "Plant")
                        .WithMany("Instructions")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GreenThumb.Models.PlantGardens", b =>
                {
                    b.HasOne("GreenThumb.Models.GardenModel", "Garden")
                        .WithMany("PlantGardens")
                        .HasForeignKey("GardenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenThumb.Models.PlantModel", "Plant")
                        .WithMany("PlantGardens")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garden");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GreenThumb.Models.GardenModel", b =>
                {
                    b.Navigation("PlantGardens");
                });

            modelBuilder.Entity("GreenThumb.Models.PlantModel", b =>
                {
                    b.Navigation("Instructions");

                    b.Navigation("PlantGardens");
                });

            modelBuilder.Entity("GreenThumb.Models.UserModel", b =>
                {
                    b.Navigation("Garden");
                });
#pragma warning restore 612, 618
        }
    }
}
